trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPOMFile: 'pom.xml'
    goals: 'package'
    options: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- script: |
    echo "Build.SourcesDirectory=$(Build.SourcesDirectory)"
    echo "System.DefaultWorkingDirectory=$(System.DefaultWorkingDirectory)"
    find $(Build.SourcesDirectory) -name "*.war"
  displayName: 'Find WAR files'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'webapp/target/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'